### ISSUE TITLE
Unable to write and read proper data

### ISSUE THREAD

**Issue by PetherPettersson** [GENIVI/vehicle_signal_interface#11]
We are unable to write and read the correct data with the vsi api. When writing a value the data doesn't show up correctly when reading it back, and dumping all data available in the shared memory with the core/tests/dump, but using the writeRecord/readRecord we are able to see it correctly.

Cause found to be in _vsi.c::vsi_fire_signal_, it takes a result struct wich contains a char* data, but then uses a reference to this pointer when it calls the core function to add the value, causing it to use wrong data.

Reproducable with the available sample program.

**Comment by dmiespdx** [comment]
This has been fixed in the latest VSI checkin.
