### ISSUE TITLE
Firing of signals by name and getting key by name not working

### ISSUE THREAD

**Issue by PetherPettersson** [GENIVI/vehicle_signal_interface#12]
We are unable to fire signals by name, or get the key associated with a name. Root cause is most likely the comparision vsi makes between keys, which compares adresses and not values. Thus trying to compare the name vsi has loaded from file and added to data storage, with a name we send from 'outside' the adresses would be different, and thus fail the lookup. But if we first get the name associated with a key, and then use this data in the fire by name we are successful.

Reproducable with available sample program, fails when trying to fire 'bar' and other signals by name.

**Comment by dmiespdx** [comment]
This has been fixed in the latest VSI checkin.
