### ISSUE TITLE
Unable to load large .vsi file

### ISSUE THREAD

**Issue by PetherPettersson** [GENIVI/vehicle_signal_interface#14]
When trying to load the vss_rel_1.vsi.FULL file we receive a segmentation fault. We haven't been able to find the root cause, but the error occurs in the _btree.c::btree_compare_function_. Cause unknown, we haven't found a specific signal or number of signals causing this, all from 86 signals to 250 and above.

Reproducable with the available sample program and sample vsi files.

**Comment by dmiespdx** [comment]
This has been fixed in the latest VSI checkin.
